### ISSUE TITLE
Support for Android 2.3

### ISSUE THREAD

**Issue by arttwo** [metova/roboguice-appcompat#1]
This implementation does not work on Android 2.3. While trying to inject a view it's crashing with following stack trace:

java.lang.RuntimeException: Unable to start activity ComponentInfo{xxx/xxx.TestActivity}: java.lang.NullPointerException: Can't inject null value into class xxx.TestActivity.button when field is not @Nullable
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1647)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1663)
        at android.app.ActivityThread.access$1500(ActivityThread.java:117)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:931)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:130)
        at android.app.ActivityThread.main(ActivityThread.java:3683)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:507)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
        at dalvik.system.NativeStart.main(Native Method)
        Caused by: java.lang.NullPointerException: Can't inject null value into class xxx.TestActivity.button when field is not @Nullable
        at roboguice.inject.ViewListener$ViewMembersInjector.reallyInjectMemberViews(ViewListener.java:179)
        at roboguice.inject.ViewListener$ViewMembersInjector.reallyInjectMembers(ViewListener.java:138)
        at roboguice.inject.ViewListener$ViewMembersInjector.injectViews(ViewListener.java:246)
        at roboguice.inject.ContextScopedRoboInjector.injectViewMembers(ContextScopedRoboInjector.java:258)
        at xxx.RoboActionBarActivity.onContentChanged(RoboActionBarActivity.java:111)
        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:210)
        at android.app.Activity.setContentView(Activity.java:1657)
        at android.support.v7.app.ActionBarActivity.superSetContentView(ActionBarActivity.java:208)
        at android.support.v7.app.ActionBarActivityDelegateBase.ensureSubDecor(ActionBarActivityDelegateBase.java:175)
        at android.support.v7.app.ActionBarActivityDelegateBase.setContentView(ActionBarActivityDelegateBase.java:133)
        at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:76)
        at xxx.BaseActivity.onCreate(BaseActivity.java:16)
        at xxx.TestActivity.onCreate(TestActivity.java:23)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1611)
        ... 11 more

**Comment by arttwo** [comment]
The same code works correctly on Android 4.3. Cannot find what is the
reason. I tested it on Android 2.3.3 Galaxy S, and also on Android 2.3
emulator. Same crash on both of them.
The crash happens while Roboguice tries to inject views. I set the content
view straight after calling super.onCreate().

Another thing is that I believe you haven't published to library to the
global Maven repository so I could only copy the source code.

Thanks,
Artur

**Comment by mccrajs** [comment]
The problem comes from the the way ActionBarActivity handles setContentView().  It first calls an ensureSubDecor() method that, if the ActionBar is enabled, sets the contentView to a custom actionBar layout for pre 3.0 devices.  This triggers view injections on a layout that does not include the views you are trying to inject.  

I am looking into a solution for this.  As a temporary work around, I would recommend getting references to your views via findViewById().  Injection of non-view dependencies should still function properly.

Source code for reference:

ActionBarActivityDelegateBase.java

```
@Override
public void setContentView(int resId) {
    ensureSubDecor();
    if (mHasActionBar) {
        final ViewGroup contentParent =
                (ViewGroup) mActivity.findViewById(R.id.action_bar_activity_content);
        contentParent.removeAllViews();
        final LayoutInflater inflater = mActivity.getLayoutInflater();
        inflater.inflate(resId, contentParent);
    } else {
        mActivity.superSetContentView(resId);
    }
}
```

```
final void ensureSubDecor() {
    if (mHasActionBar && !mSubDecorInstalled) {
        if (mOverlayActionBar) {
            mActivity.superSetContentView(R.layout.abc_action_bar_decor_overlay);
        } else {
            mActivity.superSetContentView(R.layout.abc_action_bar_decor);
        }
        mActionBarView = (ActionBarView) mActivity.findViewById(R.id.action_bar);
        mActionBarView.setWindowCallback(mActivity);

        /**
         * Progress Bars
         */
        if (mFeatureProgress) {
            mActionBarView.initProgress();
        }
        if (mFeatureIndeterminateProgress) {
            mActionBarView.initIndeterminateProgress();
        }

        /**
         * Split Action Bar
         */
        boolean splitWhenNarrow = UIOPTION_SPLIT_ACTION_BAR_WHEN_NARROW
                .equals(getUiOptionsFromMetadata());
        boolean splitActionBar;

        if (splitWhenNarrow) {
            splitActionBar = mActivity.getResources()
                    .getBoolean(R.bool.abc_split_action_bar_is_narrow);
        } else {
            TypedArray a = mActivity.obtainStyledAttributes(R.styleable.ActionBarWindow);
            splitActionBar = a
                    .getBoolean(R.styleable.ActionBarWindow_windowSplitActionBar, false);
            a.recycle();
        }

        final ActionBarContainer splitView = (ActionBarContainer) mActivity.findViewById(
                R.id.split_action_bar);
        if (splitView != null) {
            mActionBarView.setSplitView(splitView);
            mActionBarView.setSplitActionBar(splitActionBar);
            mActionBarView.setSplitWhenNarrow(splitWhenNarrow);

            final ActionBarContextView cab = (ActionBarContextView) mActivity.findViewById(
                    R.id.action_context_bar);
            cab.setSplitView(splitView);
            cab.setSplitActionBar(splitActionBar);
            cab.setSplitWhenNarrow(splitWhenNarrow);
        }

        mSubDecorInstalled = true;

        supportInvalidateOptionsMenu();
    }
}
```

**Comment by arttwo** [comment]
Hi James,

Thanks for great in deep explanation. We haven't had time to investigate
this problem deeper as we're working on switching to AS and Gradle in the
same time. I will be happy if you could let me know if you find any good
solution for that. It seems more like ActionBarCompat inconsistency since
the Roboguice port for Action Bar Sherlock seems to work.

Thanks for a great work and regards,
Artur
